import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import AOSWrapper from "../../components/AOSWrapper"; // adjust path if needed

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Billion Dollar FX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <style>{`
          body > .skiptranslate {
            display: none;
          }
          .goog-te-banner-frame.skiptranslate {
            display: none !important;
          }
          body {
            top: 0px !important;
          }
          @media print {
            #google_translate_element {
              display: none;
            }
          }
        `}</style>
      </head>
      <body className={montserrat.className}>
        <AOSWrapper>{children}</AOSWrapper>
      </body>
    </html>
  );
}
