import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import AOSWrapper from "../../components/AOSWrapper"; // adjust path if needed

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Billio Dollar FX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AOSWrapper>{children}</AOSWrapper>
      </body>
    </html>
  );
}
